from pathlib import Path

rule all:
    input:
        "output4.txt"

rule basic:
    """
    Here is some documentation.

    :input: A file
    :output: Another file
    :param a: Sets the value of ``a``
    :param b: Sets the value of ``b``
    """

    input:
        "input.txt"
    output:
        report("output.txt")
    conda:
        "envs/test1.yaml"
    params:
        a=1
    shell:
        "cat {input} > {output} && echo {params.a} >> {output}"

rule follows_basic:
    """
    Docs rhymes with socks...
    """

    input:
        "output.txt"
    output:
        "output2.txt"
    resources:
        mem_mb=2
    shell:
        "echo 'output.txt content = ' > {output} && cat {input} >> {output}"

rule also_follows_basic:
    """
    Docs rhymes with clocks...
    """

    input:
        "output.txt"
    output:
        "output3.txt"
    shell:
        "touch {output}"

checkpoint gen_random:
    """
    Generates a random number (between 1 and 3) of empty files.
    """

    input:
        rules.also_follows_basic.output
    output:
        directory("random")
    shell:
        """
        for ii in {1..$(( $RANDOM % 3 + 1 ))}; do
            touch {output}/$ii.tmp
        done
        """

def random_files(wildcards):
    checkpoints.gen_random.get()
    return list(Path("random").glob("*.tmp"))

rule the_end:
    input:
        random_files
    output:
        "output4.txt"
    shell:
        "cat {input} > {output}"
