name: coverage

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install Hatch
      run: pip install --upgrade --pre hatch

    - name: Generate coverage statistic
      run: |
        hatch run cov | tee output.log
        echo "COVERAGE=$(grep TOTAL output.log | tr -s ' ' | cut -f 4 -d ' ')" >> $GITHUB_ENV

    - name: Create badge
      uses: schneegans/dynamic-badges-action@v1.1.0 # instructions here: https://github.com/Schneegans/dynamic-badges-action
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: bbe05fc2211ebcc2ce35d446223426e0
        filename: coverage-badge.json
        label: coverage
        message: ${{ env.COVERAGE }}
        color: green
