name: coverage

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'

    - name: Install Hatch
      run: pip install --upgrade --pre hatch

    # - name: Set up cache
    #   uses: actions/cache@v2
    #   id: cached-hatch-datadir
    #   with:
    #     path: .hatch-data
    #     key: hatch-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/pyproject.toml') }}

    - name: Generate coverage statistic
      run: |
        hatch --data-dir .hatch-data run cov | tee output.log
        echo "COVERAGE=$(grep TOTAL output.log | tr -s ' ' | cut -f 6 -d ' ')" >> $GITHUB_ENV

    - name: Create badge
      uses: schneegans/dynamic-badges-action@v1.1.0 # instructions here: https://github.com/Schneegans/dynamic-badges-action
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: bbe05fc2211ebcc2ce35d446223426e0
        filename: coverage-badge.json
        label: coverage
        message: ${{ env.COVERAGE }}
        color: green
