name: coverage

on: [push]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install poetry and deps
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install -v
    - name: Generate coverage statistic
      run: |
        poetry run tox -e coverage
        echo "COVERAGE=$(poetry run coverage report --precision 2 | grep TOTAL | tr -s ' ' | cut -f 4 -d " ")" >> $GITHUB_ENV
    - name: Create Badge
      uses: schneegans/dynamic-badges-action@v1.1.0 # instructions here: https://github.com/Schneegans/dynamic-badges-action
      with:
        auth: ${{ secrets.GIST_SECRET }}
        gistID: bbe05fc2211ebcc2ce35d446223426e0
        filename: coverage-badge.json
        label: coverage
        message: ${{ env.COVERAGE }}
        color: green
